name: Commands
on:
  workflow_dispatch:
jobs:
  exec_cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: step_1
        run: |
          #docker pull rabbitmq:alpine
          #docker run --hostname theRabbit --name aRabbit rabbitmq:alpine
          #docker logs aRabbit
          npm install
          npm run dev
      #- name: step_2
        #run: |
          #git config --global user.email "pobre@mail.com"
          #git config --global user.name "pobre"
          #git add .
          #git commit -m 'Commiting'
          #git push origin main
