name: Commands
on:
  workflow_dispatch:
jobs:
  get_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RabbitMQ
        run: |
          #docker pull rabbitmq:alpine
          #docker run --hostname theRabbit --name aRabbit rabbitmq:alpine
          #docker logs aRabbit
      - name: AppTest
        run: |
          docker build --tag docker-review .
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myImage
          path: ./
  run_images:
    needs: get_images
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: myImage
      - name: run_container
        run: |
          docker run -d -p 4000:3000 docker-review
      - name: get from service app_test
        run: |
          http://localhost:4000
          echo 'Done!'



      #- name: Commit
        #run: |
          #git config --global user.email "pobre@mail.com"
          #git config --global user.name "pobre"
          #git add .
          #git commit -m 'Commiting'
          #git push origin main
