name: Commands
on:
  workflow_dispatch:
jobs:
  get_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RabbitMQ
        run: |
          #docker pull rabbitmq:alpine
          #docker run --hostname theRabbit --name aRabbit rabbitmq:alpine
          #docker logs aRabbit
      - name: AppTest
        run: |
          docker build --tag docker-review .
  #run_images:
    #needs: get_images
    #runs-on: ubuntu-latest
    #services:
      #set_docker-review:
        #image: dockerhub-username:docker-review
        #ports:
          #- 4000:3000
    #steps:
      #- name: get from service app_test
        #run: http://localhost:4000



      #- name: Commit
        #run: |
          #git config --global user.email "pobre@mail.com"
          #git config --global user.name "pobre"
          #git add .
          #git commit -m 'Commiting'
          #git push origin main
