name: Commands
on:
  workflow_dispatch:
jobs:
  exec_cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: step_1
        run: |
          #docker pull rabbitmq:alpine
          #docker run --hostname theRabbit --name aRabbit rabbitmq:alpine
          #docker logs aRabbit
          docker build --tag docker-review .
          docker run -d -p 4000:3000 --name docker-review docker-review:latest
          docker container logs --details docker-review
          curl localhost:4000
          curl localhost:4000/costumer
          docker container logs --details docker-review
          docker stop docker-review
      #- name: step_2
        #run: |
          #git config --global user.email "pobre@mail.com"
          #git config --global user.name "pobre"
          #git add .
          #git commit -m 'Commiting'
          #git push origin main
